language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: gOfe1LcmQBaY0HQgByJYWjm6dK4xJhCJf62tFK8qwycDSpWHRhvZYlVmyLwc/N34VtoNXCzQzdzRsaXbGT8zp7Hd7dzLIAn+h49Db4KqrH0lpaCfXOUcY8wgGeFafbT3bWq6Swtny2E1VGjvqqkYPv7N8H0ufRFDYnjRlvlhXQSoUzY8YR86NHivaLnr2krRDm4U8ZhnPsI2O7ewF/ig0FGuAF78NbrNoC4c/fYSFcO9tFBay9VG+NSU5uVh6vUpUZP0c5KWo3RE3hT3oBLS0rR27pMh4Kh+Ax2+3OfF3UdQME8D388bZUK/TS6huUM0zRWKbkDb+JNuD/Y+hihJg6EANaQe2D0r2Cw8QVsH8+pAfkNIozabnwd/mNYiFJOpTM0RIKPc5mKvL1DrT7qJ7Inpm1t7EjcP7GSun+lAeQe3APvSSKIqlhdbuAZOEfPAgHQybbHu9jPMYBi8WZgFIEaQ+pyI+8XBG6tbvVFK+LALJcS9Q4aTQmw4UQaZyCjkHgHrNwtbGuMy/gTDS0AcO2bgO5t6L6UG+6L4qdbDlXFsxsJjE3SLdNpTzyok6JjjOKulDfWFHQY4c0QIAWyztOQXRgE2oedX2AIAQGKHNwfStn62ca87UBJT2TZjwPLQ/3WjF2TKbI1zFsKRW/sE4bmAqR/p8QdEJbhvxgk2w3Y=
  app: radiant-savannah-66015
  on:
    repo: JasminTrotter/student-portal-api
